const test = require('./index')

console.log(test.getMBName())
console.log(test.getMBRevision())
console.log(test.getMBSerial())
console.log(test.getUser())
console.log(test.getPCName())
console.log(test.getGPUName())
console.log(test.getPowerScheme())
console.log(test.getMemSize())
console.log(test.getMemSpeed())