const test = require('./index')

console.log(test.get.MBName())
console.log(test.get.MBRevision())
console.log(test.get.MBSerial())
console.log(test.get.User())
console.log(test.get.PCName())
console.log(test.get.GPUName())
console.log(test.get.PowerScheme())
console.log(test.get.MemSize())
console.log(test.get.MemSpeed())
console.log(test.get.UserDirectory())
console.log(test.get.RootDirectory())