const sys = require('./index')

console.log(sys.get.MBName())
console.log(sys.get.MBRevision())
console.log(sys.get.MBSerial())
console.log(sys.get.User())
console.log(sys.get.PCName())
console.log(sys.get.GPUName())
console.log(sys.get.PowerScheme())
console.log(sys.get.MemSize())
console.log(sys.get.MemSpeed())
console.log(sys.get.UserDirectory())
console.log(sys.get.RootDirectory())
console.log(sys.get.DesktopDirectory())